name: Pull release/* into develop

on:
  push:
    branches:
      - release/*

jobs:
  pr_rc_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset To RC branch
        run: |
          git fetch origin ${{ github.sha }}:${{ github.sha }}
          git reset --hard ${{ github.sha }}
      - name: Extract Release Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Create Pull Request from RC -> develop
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}-to-develop
