name: Pull release/* into develop

on:
  push:
    branches:
      - release/*
      - master

jobs:
  master_to_rc:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2
      - name: Extract release branch name
        run: |
          git fetch origin
          git branch -l -r 'origin/release/*' --sort=-committerdate | head -n 1 | sed -e 's/^[ \t]*//'
      # - name: Reset To RC branch
      #   run: |
      #     git fetch origin ${{ github.sha }}:${{ github.sha }}
      #     git reset --hard ${{ github.sha }}
      # - name: Reset To RC branch
      #   run: |
      #     git fetch origin ${{ github.sha }}:${{ github.sha }}
      #     git reset --hard ${{ github.sha }}
      # - name: Create Pull Request from master -> RC
      #   uses: peter-evans/create-pull-request@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: merge-master-to-rc
      #     title: "Merge master changes into RC"

  rc_to_dev:
    if: contains(github.ref,'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset To RC branch
        run: |
          git fetch origin ${{ github.sha }}:${{ github.sha }}
          git reset --hard ${{ github.sha }}
      - name: Extract Release Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Create Pull Request from RC -> develop
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: merge-${{ steps.extract_branch.outputs.branch }}-to-develop
          title: "Merge RC changes into develop"
