name: Pull release/* into develop

on:
  push:
    branches:
      - release/*

jobs:
  pr_rc_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Create Pull Request from RC -> develop
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
